- name: Gather EC2 facts
  ansible.builtin.setup:


- name: Install Nginx on Amazon Linux 3
  ansible.builtin.dnf:
    name: nginx
    state: present
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution == "Amazon"



- name: Template index file for Amazon Linux
  ansible.builtin.template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    owner: nginx
    group: nginx
    mode: '0644'
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution == "Amazon"



- name: Enable and start Nginx (Amazon Linux)
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: started
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution == "Amazon"